spring:
  data:
    mongodb:
      uri: mongodb+srv://${properties.db.user}:${properties.db.password}@cluster0.j0lz3tg.mongodb.net/${properties.db.name}?retryWrites=true&w=majority

  output:
    ansi:
      enabled: always

logging:
  level:
    org.springframework.data.mongodb.core.MongoTemplate: debug
    org.hibernate.SQL: debug
    org.hibernate.type.descriptor.sql.BasicBinder: trace

springdoc:
  api-docs:
    path: /api-docs
    groups:
      enabled: true
  swagger-ui:
    path: swagger.html
    display-request-duration: true
    groups-order: DESC
