spring:
  data:
    mongodb:
      uri: mongodb://${properties.db.user}:${properties.db.password}@localhost:27020/${properties.db.name}
#      authentication-database: admin
#      host: localhost
#      port: 8000
#      username: ${properties.db.user}
#      password: ${properties.db.password}
#      database: ${properties.db.name}
  #      replica-set-name: replicaSet

  output:
    ansi:
      enabled: always

logging:
  level:
    org.springframework.data.mongodb.core.MongoTemplate: debug
    org.hibernate.SQL: debug
    org.hibernate.type.descriptor.sql.BasicBinder: trace

springdoc:
  api-docs:
    path: /api-docs
    groups:
      enabled: true
  swagger-ui:
    path: swagger.html
    display-request-duration: true
    groups-order: DESC
